Hey,
I am applying for the full stack intern role at Google. I like building things end to end writing the API and then actually seeing it work when someone clicks a button. That's the part I enjoy. Not the planning, not the meetings, just the part where code runs and does something useful.
My main project is this e-commerce backend I built in Go with Fiber and PostgreSQL. Started as a single main.go file with everything dumped in it. API calls everywhere, zero structure. I was up at 2 AM debugging this GORM error "ERROR: insert or update on table "orders" violates foreign key constraint" and I realized my Preload was loading the wrong association. I had no idea why. I ended up refactoring the whole thing into this DTO Handler Service Repository setup just so I could debug it without losing my mind. Set up JWT with bcrypt, Stripe, Twilio, Docker Compose. The first few GitHub commits are embarrassing but that's how you know I actually built it.
I also made this Chrome extension for bulk unsubscribing YouTube channels. Had to reverse engineer their SAPISIDHASH auth flow. The tricky part was injecting into the MAIN execution context because regular content scripts couldn't access what I needed. Spent two days figuring out why my script couldn't read ytInitialData turns out YouTube's own JS hadn't hydrated the page yet so I had to wait for it. Rate limiting, pagination, all that. I remember that bug more than any feature that just worked. honestly it was more frustrating than interesting but I learned from it.
At Tikun Technologies I scraped 10k+ Google Maps reviews with BeautifulSoup. The HTML was a mess. Class names changed, some reviews had no text, some had weird unicode characters that broke my parser. I just had to clean it up and dump it into JSON. Real world data sucks. I guess at Google you deal with the same thing but way more of it.
I have this NPTEL cert from IIT Kanpur Top 5% in Cloud, IoT and Edge MLand I've solved 500+ DSA problems. Those are fine. But what I actually like is when something breaks and I have to trace it from the browser's network tab all the way down to the query. That's when I actually learn things.
I want to work at Google because I want to see how real production systems are built. Not tutorials. Not side projects. The actual stuff that handles real traffic. I want to ship things that matter.
Thanks,
Saurabh Kumar
(+91) 8877887996
meetsaurabh78@gmail.com